language: java

jdk:
  #- openjdk8
  #- oraclejdk11
  - openjdk11

services:
  - postgresql

before_script:
  - chmod +x ./gradlew
  - psql -c 'create database readingbat;' -U postgres
  - ./gradlew flywayClean flywayMigrate flywayInfo
#  - sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'none'

script:
  - ./gradlew check #jacocoTestReport
  - ./gradlew flywayClean flywayMigrate
  - ../gradlew run --args="-config=src/test/resources/application-test.conf" &
  - sleep 20
  - ~/node_modules/.bin/cypress run --record --key 5ee5de19-1e84-4807-a199-5c70fda2fe5d
  - curl http://localhost:8080/shutdown

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#  - ./gradlew jacocoTestReport coveralls

notifications:
  email:
    - pambrose@mac.com