language: java

jdk:
  #- openjdk8
  #- oraclejdk11
  - openjdk11

services:
  - postgresql

before_script:
  - chmod +x gradlew
  - psql -c 'create database readingbat;' -U postgres
  - ./gradlew flywayClean flywayMigrate
#  - sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'none'

script:
  - ./gradlew check #jacocoTestReport

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#  - ./gradlew jacocoTestReport coveralls

notifications:
  email:
    - pambrose@mac.com