/*
 * Copyright © 2023 Paul Ambrose (pambrose@mac.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.github.readingbat.pages

import com.github.pambrose.common.util.isNull
import com.github.pambrose.common.util.pathOf
import com.github.pambrose.common.util.pluralize
import com.github.pambrose.common.util.toDoubleQuoted
import com.github.pambrose.common.util.toRootPath
import com.github.readingbat.common.ClassCode
import com.github.readingbat.common.Constants.ADMIN_FUNC
import com.github.readingbat.common.Constants.ICONS
import com.github.readingbat.common.Endpoints.CHALLENGE_ROOT
import com.github.readingbat.common.Endpoints.CSS_ENDPOINT
import com.github.readingbat.common.Endpoints.PRIVACY_ENDPOINT
import com.github.readingbat.common.Endpoints.STATIC_ROOT
import com.github.readingbat.common.Endpoints.TAILWIND_CSS_ENDPOINT
import com.github.readingbat.common.FormFields.RETURN_PARAM
import com.github.readingbat.common.Message
import com.github.readingbat.common.Message.Companion.EMPTY_MESSAGE
import com.github.readingbat.common.Property
import com.github.readingbat.common.Property.ANALYTICS_ID
import com.github.readingbat.common.Property.TAILWIND_ENABLED
import com.github.readingbat.common.TwClasses
import com.github.readingbat.common.User
import com.github.readingbat.dsl.LanguageType
import com.github.readingbat.dsl.LanguageType.Companion.languageTypeList
import com.github.readingbat.dsl.LanguageType.Java
import com.github.readingbat.dsl.LanguageType.Kotlin
import com.github.readingbat.dsl.LanguageType.Python
import com.github.readingbat.dsl.ReadingBatContent
import com.github.readingbat.dsl.isProduction
import com.github.readingbat.pages.HelpAndLogin.helpAndLogin
import io.ktor.http.ContentType.Text.CSS
import io.ktor.server.routing.Route
import io.ktor.server.routing.RoutingHandler
import io.ktor.server.routing.get
import io.ktor.server.routing.post
import kotlinx.html.BODY
import kotlinx.html.Entities.nbsp
import kotlinx.html.FlowOrInteractiveOrPhrasingContent
import kotlinx.html.FormMethod
import kotlinx.html.HEAD
import kotlinx.html.HTMLTag
import kotlinx.html.a
import kotlinx.html.button
import kotlinx.html.div
import kotlinx.html.form
import kotlinx.html.id
import kotlinx.html.li
import kotlinx.html.link
import kotlinx.html.nav
import kotlinx.html.onClick
import kotlinx.html.onSubmit
import kotlinx.html.p
import kotlinx.html.script
import kotlinx.html.span
import kotlinx.html.style
import kotlinx.html.submitInput
import kotlinx.html.title
import kotlinx.html.ul
import kotlinx.html.unsafe

internal object PageUtils {
  private const val READING_BAT = "ReadingBat"

  fun HEAD.headDefault() {
    link {
      rel = "stylesheet"
      href = CSS_ENDPOINT
      type = CSS.toString()
    }

    // From: https://favicon.io/emoji-favicons/glasses/
    val prefix = pathOf(STATIC_ROOT, ICONS)
    link {
      rel = "apple-touch-icon"
      sizes = "180x180"
      href = "$prefix/apple-touch-icon.png"
    }
    link {
      rel = "icon"
      type = "image/png"
      sizes = "32x32"
      href = "$prefix/favicon-32x32.png"
    }
    link {
      rel = "icon"
      type = "image/png"
      sizes = "16x16"
      href = "$prefix/favicon-16x16.png"
    }
    link {
      rel = "manifest"
      href = "$prefix/site.webmanifest"
    }

    // Tailwind CSS support (controlled by readingbat.site.tailwindEnabled)
    if (TAILWIND_ENABLED.getProperty(false)) {
      if (isProduction()) {
        // Production: use pre-built CSS generated by Tailwind CLI (./gradlew :readingbat-core:tailwindBuild)
        link {
          rel = "stylesheet"
          href = TAILWIND_CSS_ENDPOINT
          type = CSS.toString()
        }
      } else {
        // Development: use Tailwind CDN for instant exploration (not for production use)
        script { src = "https://cdn.tailwindcss.com" }
        // CDN config with addBase plugin to override preflight rules that conflict
        // with CssContent.kt. Mirrors tailwind-input.css @layer base rules.
        // Plugin addBase() is guaranteed to inject after preflight in the base layer.
        script {
          rawHtml(
            """
            tailwind.config = {
              prefix: 'tw-',
              theme: {
                extend: {
                  colors: {
                    'rb-link': '#0000DD',
                    'rb-visited': '#551A8B',
                    'rb-incomplete': '#F1F1F1',
                    'rb-correct': '#4EAA3A',
                    'rb-wrong': '#FF0000',
                    'rb-header': '#419DC1',
                    'rb-code-stripe': '#0600EE',
                  },
                  fontFamily: {
                    'sans': ['verdana', 'arial', 'helvetica', 'sans-serif'],
                  },
                },
              },
              plugins: [
                function({ addBase }) {
                  addBase({
                    'html, body': { 'font-size': '16px', 'font-family': 'verdana, arial, helvetica, sans-serif' },
                    'body': { 'display': 'block', 'margin': '8px', 'line-height': 'normal', 'background-color': 'white' },
                    'h1, h2, h3, h4': { 'font-weight': 'bold' },
                    'h2': { 'font-size': '150%', 'margin': '0.83em 0' },
                    'h3': { 'margin': '1em 0' },
                    'ol': { 'list-style-type': 'decimal', 'padding-left': '2em' },
                    'ul': { 'list-style-type': 'disc', 'padding-left': '2em' },
                    'li': { 'margin-top': '10px' },
                    'p': { 'max-width': '800px', 'line-height': '1.5', 'margin-top': '1em', 'margin-bottom': '1em' },
                    'img': { 'display': 'inline', 'max-width': 'none' },
                    'table': { 'border-collapse': 'separate' },
                    ':link': { 'color': '#0000DD' },
                    ':visited': { 'color': '#551A8B' },
                    'td': { 'vertical-align': 'middle' },
                    'a': { 'text-decoration': 'none' },
                    'a:hover': { 'color': 'red' },
                    'th, td': { 'padding': '1px', 'text-align': 'left' },
                    'th': { 'font-size': '115%' },
                    '.h1': { 'font-size': '300%' },
                    '.h2': { 'font-size': '166%', 'text-decoration': 'none' },
                    '.h3': { 'font-size': '120%' },
                    'td.no': { 'min-width': '22px', 'background-color': 'red' },
                    'td.ok': { 'min-width': '22px', 'background-color': 'green' },
                    'nav ul': { 'list-style-type': 'none', 'padding': '0', 'margin': '0' },
                    'nav li': { 'display': 'inline', 'border': '1px solid', 'border-width': '1px 1px 0 1px', 'margin': '0 25px 0 6px' },
                    'nav li a': { 'padding': '0 40px' },
                    '#selected': { 'position': 'relative', 'top': '1px', 'background': 'white' },
                    'input[type="submit"], button': {
                      'background-color': '#F1F1F1',
                      'border': '1px solid #D1D5DB',
                      'border-radius': '0.25rem',
                      'padding': '2px 8px',
                      'cursor': 'pointer',
                      'box-shadow': '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
                    },
                    'input[type="submit"]:active, button:active': {
                      'box-shadow': 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
                      'transform': 'translateY(1px)',
                    },
                    'input[type="text"], input[type="password"]': { 'border': '1px solid #767676', 'background-color': 'white' },
                    'textarea': { 'border': '1px solid #767676', 'background-color': 'white' },
                  })
                }
              ],
            }
            """,
          )
        }
      }
    }

    title(READING_BAT)

    val analyticsId = ANALYTICS_ID.getPropertyOrNull() ?: ""
    if (isProduction() && analyticsId.isNotBlank()) {
      script {
        async = true
        src = "https://www.googletagmanager.com/gtag/js?id=$analyticsId"
      }
      script {
        rawHtml(
          """
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '$analyticsId');
          """,
        )
      }
    }

    // loadRecaptchaScript(recaptchaConfig)
  }

  fun HEAD.clickButtonScript(vararg buttonNames: String) {
    buttonNames.forEach { buttonName ->
      script {
        rawHtml(
          """
          function click$buttonName(event) {
            if (event != null && event.keyCode == 13) {
              event.preventDefault();
              document.getElementById('$buttonName').click();
            }
          }
          """.trimIndent(),
        )
      }
    }
  }

  fun BODY.bodyTitle() {
    // Tailwind equivalents: tw-mb-0, tw-text-4xl, tw-pl-1
    // Inline styles kept as fallback when Tailwind is disabled
    div(classes = "tw-mb-0") {
      style = "margin-bottom:0em"
      a {
        href = "/"
        span(classes = "tw-text-4xl") {
          style = "font-size:200%"
          +READING_BAT
        }
      }
      span(classes = "tw-pl-1") {
        style = "padding-left:5px"
        +"code reading practice"
      }
    }
  }

  fun BODY.bodyHeader(
    content: ReadingBatContent,
    user: User?,
    languageType: LanguageType,
    loginAttempt: Boolean,
    loginPath: String,
    displayWelcomeMsg: Boolean,
    activeClassCode: ClassCode,
    msg: Message = EMPTY_MESSAGE,
  ) {
    helpAndLogin(content, user, loginPath, activeClassCode.isEnabled)
    bodyTitle()

    p { if (displayWelcomeMsg) +"Welcome to ReadingBat." else rawHtml(nbsp.text) }

    if (loginAttempt && user.isNull())
      p {
        span(classes = "tw-text-red-500") {
          style = "color:red"
          +"Failed to login -- incorrect email or password"
        }
      }

    p {
      span(classes = "tw-text-green-500 tw-max-w-[800px]") {
        style = "color:green; max-width:800"
        if (msg.isNotBlank) +(msg.toString()) else rawHtml(nbsp.text)
      }
    }

    div(classes = "tw-pt-2.5 tw-min-w-screen tw-clear-both") {
      style = "padding-top:10px; min-width:100vw; clear:both"
      nav {
        ul {
          languageTypeList
            .filter { content[it].isNotEmpty() }
            .forEach { lang ->
              li(classes = "h2") {
                if (languageType == lang)
                  id = "selected"
                this@bodyHeader.addLink(lang.name, pathOf(CHALLENGE_ROOT, lang.languageName))
              }
            }
        }
      }
    }

    div(classes = "tw-border-t tw-clear-both") {
      style = "border-top: 1px solid; clear: both"
    }
  }

  fun BODY.addLink(text: String, url: String, newWindow: Boolean = false) =
    a {
      href = url
      if (newWindow) target = "_blank"
      +text
    }

  fun BODY.privacyStatement(returnPath: String) =
    p(classes = TwClasses.INDENT_1EM) {
      a {
        href = "$PRIVACY_ENDPOINT?$RETURN_PARAM=$returnPath"
        +"Privacy Statement"
      }
    }

  private fun BODY.linkWithIndent(url: String, text: String, marginLeft: String = "1em") {
    if (url.isNotEmpty()) {
      div {
        style = "font-size:120%; margin-left:$marginLeft"
        p {
          a {
            href = url
            rawHtml("⬅ $text")
          }
        }
      }
    }
  }

  fun enrolleesDesc(enrollees: List<User>): String {
    val studentCount = if (enrollees.isEmpty()) "No" else enrollees.count().toString()
    return " - $studentCount ${"student".pluralize(enrollees.count())} enrolled"
  }

  @Suppress("unused")
  fun BODY.confirmingButton(text: String, endpoint: String, msg: String) {
    form(classes = "tw-m-0") {
      style = "margin:0"
      action = endpoint
      method = FormMethod.get
      onSubmit = "return confirm('$msg')"
      submitInput(classes = "tw-align-middle tw-mt-px tw-mb-0") {
        style = "vertical-align:middle; margin-top:1; margin-bottom:0"
        value = text
      }
    }
  }

  fun BODY.adminButton(text: String, endpoint: String, confirm: String) {
    button(classes = TwClasses.ADMIN_BUTTON) {
      onClick = "$ADMIN_FUNC(${confirm.toDoubleQuoted()}, ${endpoint.toDoubleQuoted()})"
      +text
    }
  }

  fun BODY.displayMessage(msg: Message) = if (msg.isNotBlank) +(msg.toString()) else rawHtml(nbsp.text)

  private val rootVals = listOf("", "/", Java.contentRoot, Python.contentRoot, Kotlin.contentRoot)

  fun BODY.backLink(vararg pathElems: String = arrayOf("/")) {
    if (pathElems.size == 1 && pathElems[0] in rootVals)
      linkWithIndent(pathElems.toList().toRootPath(), "Home")
    else
      linkWithIndent(pathElems.toList().toRootPath(), "Back")
  }

  fun BODY.loadPingdomScript() {
    Property.PINGDOM_URL.getPropertyOrNull()?.also {
      if (it.isNotBlank())
        script {
          src = it
          async = true
        }
    }
  }

  fun BODY.loadStatusPageDisplay() {
    Property.STATUS_PAGE_URL.getPropertyOrNull()?.also { if (it.isNotBlank()) script { src = it } }
  }

  fun HTMLTag.rawHtml(html: String) = unsafe { raw(html) }

  @Suppress("unused")
  fun Route.getAndPost(path: String, body: RoutingHandler) {
    get(path, body)
    post(path, body)
  }

  private fun hideShowJs(formName: String, fieldName: String) =
    """
      var pw=document.$formName.$fieldName.type=="password";
      document.$formName.$fieldName.type=pw?"text":"password";
      return false;
    """.trimIndent()

  fun FlowOrInteractiveOrPhrasingContent.hideShowButton(formName: String, fieldName: String, sizePct: Int = 85) {
    button {
      style = "font-size:$sizePct%"
      onClick = hideShowJs(formName, fieldName)
      +"show/hide"
    }
  }

  fun encodeUriElems(vararg elems: Any) = elems.joinToString("+'/'+") { "encodeURIComponent('$it')" }
}
